name: Install
description: Install node and pnpm

inputs:
  node-version:
    description: "Override the default node version, or override what is specified in your project's volta config"
    required: false
    default: lts/*
  args:
    description: 'Directly pass args to pnpm'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install
      uses: wyvox/action-setup-pnpm@v3
      with:
        node-version-file: ''
        node-version: ${{ inputs.node-version }}
        pnpm-version: ''
        node-registry-url: 'https://registry.npmjs.org/'
        args: ${{ inputs.args }}
